import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

test("market snapshot separates public requests from verified users", async () => {
  const market = await fs.readFile(path.resolve("MARKET.md"), "utf8");
  const snapshot = JSON.parse(await fs.readFile(path.resolve("evidence/market-snapshot-2026-07-15.json"), "utf8"));
  assert.match(market, new RegExp(`Observed ${snapshot.observationDate}`));
  assert.match(market, new RegExp(`\\| npm downloads, ${snapshot.aienvmap.npm.start} through ${snapshot.aienvmap.npm.end} \\| ${snapshot.aienvmap.npm.downloads} \\|`));
  assert.match(market, /Published npm versions \| 2/);
  assert.match(market, /signed-provenance 0\.1\.1/);
  assert.match(market, /requests, not unique people/);
  assert.match(market, /zero public stars, forks, and independent verified cases/);
  assert.match(market, /manual bundle/);
  assert.match(market, /Do not build an agent package manager/);
  assert.match(market, /use APM only to distribute the bounded advisory skill/);
  assert.match(market, /Microsoft APM/);
  assert.match(market, new RegExp(`${snapshot.repositories["microsoft/apm"].stars.toLocaleString("en-US")} stars; latest v0\\.25\\.0`));
  assert.match(market, new RegExp(`${snapshot.repositories["jdx/mise"].stars.toLocaleString("en-US")} stars; latest v2026\\.7\\.6`));
  assert.match(market, /MCP server exposes tools, tasks, environment variables, and config/);
  assert.match(market, /agent-package SBOMs/);
  assert.match(market, /Devbox/);
  assert.match(market, /Flox/);
  assert.match(market, /AI runtime CLI setup/);
  assert.match(market, /envinfo/);
  assert.match(market, /multi-path evidence, AI decisions, and change handoff/);
  assert.equal(snapshot.aienvmap.independentOutcomeVerifiedCases, 0);
  assert.match(snapshot.method, /not quality, users, retention, or successful-use evidence/);
});
