import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

test("packaged aienvmap skill points AI agents to current startup contracts", async () => {
  const skill = await fs.readFile(path.resolve(".agents/skills/aienvmap/SKILL.md"), "utf8");

  assert.match(skill, /npx aienvmap start/);
  assert.match(skill, /npx aienvmap onboard/);
  assert.match(skill, /npx aienvmap discover --json/);
  assert.match(skill, /before assuming automatic pickup worked/);
  assert.match(skill, /aiEntry/);
  assert.match(skill, /copyPastePrompt/);
  assert.match(skill, /fallbackPrompt/);
  assert.match(skill, /Use \/ Skip \/ Start/);
  assert.match(skill, /multiple AI agents or humans/);
  assert.match(skill, /full compliance SBOM scanner/);
  assert.match(skill, /AI coordination layer/);
  assert.match(skill, /Syft, Trivy, Grype, Dependency-Track/);
  assert.match(skill, /reconcile --json/);
  assert.match(skill, /--full-packages/);
  assert.match(skill, /installerEvidence/);
  assert.match(skill, /managerEvidence/);
  assert.match(skill, /externalEvidenceDecision/);
  assert.match(skill, /digest-mismatch/);
  assert.match(skill, /--clear-import --write/);
  assert.match(skill, /component-drift-review/);
  assert.match(skill, /componentInventory\.truncated/);
  assert.match(skill, /identityConfidence/);
  assert.match(skill, /fallback-only/);
  assert.match(skill, /list-and-version-path-match/);
  assert.match(skill, /configured-root-version-path-match/);
  assert.match(skill, /external symlink/);
  assert.match(skill, /Read `externalSbom` during startup/);
  assert.match(skill, /Read `aiDecisionEnvelope` first/);
  assert.match(skill, /requiresHumanApprovalBefore/);
  assert.match(skill, /global installs/);
  assert.match(skill, /--portable --json/);
  assert.match(skill, /review it before sharing/);
  assert.match(skill, /--portable-from/);
  assert.match(skill, /pseudonymous fact-set tokens/);
  assert.match(skill, /--portable-compare/);
  assert.match(skill, /reasonCodes/);
  assert.match(skill, /refresh-import-required/);
  assert.match(skill, /python\.managerInventories/);
  assert.match(skill, /manager-native evidence/);
  assert.match(skill, /node\.managerInventories\.volta/);
  assert.match(skill, /inventory-and-image-path-match/);
  assert.match(skill, /node\.managerInventories\.mise/);
  assert.match(skill, /installed-json-path-match/);
  assert.match(skill, /ownershipProven: true/);
  assert.match(skill, /removalAuthorized: false/);
  assert.match(skill, /otherRuntimes\.java\.discoveryEvidence/);
  assert.match(skill, /Windows Registry, macOS `java_home`, and Linux alternatives/);
  assert.match(skill, /otherRuntimes\.java\.runtimeMetadata/);
  assert.match(skill, /jre-or-runtime-image/);
  assert.match(skill, /sibling-`javac` evidence/);
  assert.match(skill, /otherRuntimes\.java\.buildTools\.bindings/);
  assert.match(skill, /Project `mvnw`\/`gradlew` wrappers take precedence/);
  assert.match(skill, /aiDecision\.javaManagerEvidence/);
  assert.match(skill, /canonical-home-in-install-root/);
  assert.match(skill, /every jenv `registered-runtime-routing` entry prove routing only/);
  assert.match(skill, /aiAdoptionDecision/);
  assert.match(skill, /compact use\/recommend\/start\/skip block/);
  assert.match(skill, /recommendation\.decisionRoutine/);
  assert.match(skill, /recommendation\.shortPitch/);
  assert.match(skill, /recommendation\.evidenceDocs/);
  assert.match(skill, /qualitySignals/);
  assert.match(skill, /examples\/ai-adoption-guide\.md/);
  assert.match(skill, /examples\/ai-workspace-case-study\.md/);
  assert.match(skill, /onboard --agents cursor,copilot/);
  assert.match(skill, /aiSession/);
  assert.match(skill, /\.aienvmap\/discovery\.json/);
  assert.match(skill, /maintenance\.nextCommand/);
  assert.match(skill, /\.aienvmap\/status\.json/);
  assert.match(skill, /npx aienvmap start --json/);
  assert.match(skill, /artifactFreshness\.state/);
  assert.match(skill, /agentPointers\.discovery/);
  assert.match(skill, /aienvmap discover --json/);
  assert.match(skill, /aiDiscovery/);
  assert.match(skill, /aiDiscovery\.decision/);
  assert.match(skill, /fallback-required/);
  assert.match(skill, /aiDiscovery\.startupChecklist/);
  assert.match(skill, /aiDiscovery\.aiEntry\.readFirst/);
  assert.match(skill, /aiDiscovery\.copyPastePrompt/);
  assert.match(skill, /compatible older alias/);
  assert.match(skill, /Treat `resume` as the more detailed compatible routine/);
  assert.match(skill, /beforeEnvironmentChange/);
  assert.match(skill, /afterEnvironmentChange/);
  assert.match(skill, /Automatic discovery is best-effort/);
  assert.match(skill, /discovery:/);
  assert.match(skill, /followUpPlan/);
  assert.match(skill, /nextCommand/);
  assert.match(skill, /npx aienvmap sync/);
  assert.match(skill, /npx aienvmap demo/);
  assert.match(skill, /review-before-env-change/);
  assert.match(skill, /without heavy locks or surprise failures/);
  assert.match(skill, /operationalSafety/);
  assert.match(skill, /must not be changed automatically/);
  assert.match(skill, /Local source edits can continue/);
  assert.match(skill, /--inspect-home <absolute-home>/);
  assert.match(skill, /examples\/inspect-homes\.json/);
  assert.match(skill, /non-identifying aliases/);
  assert.match(skill, /at most eight explicit homes/);
  assert.match(skill, /never enumerates system users/);
  assert.match(skill, /never invokes discovered executables/);
  assert.match(skill, /entries\[\]\.evidence/);
  assert.match(skill, /administrator file-presence evidence/);
  assert.match(skill, /--home-evidence aggregate\.json --alias build-a/);
  assert.match(skill, /owning user to run its `nextSafeCommand`/);
  assert.match(skill, /--owner-verification/);
  assert.match(skill, /category coverage only/);
  assert.match(skill, /never proves identity/);
  assert.match(skill, /--case-summary portable\.json --markdown/);
  assert.match(skill, /writes nothing and uploads nothing/);
  assert.match(skill, /never completes human verification/);
  assert.match(skill, /aiDecision\.clarification\.required/);
  assert.match(skill, /default to `need-more-evidence`/);
  assert.match(skill, /preserve `keep-intentional` as a valid answer/);
  assert.match(skill, /never infer cleanup intent from duplication/);
  assert.match(skill, /intentional-node-versions: 20,22/);
  assert.match(skill, /intentional-java-versions: 17,21/);
  assert.match(skill, /Java remains information-only/);
  assert.match(skill, /Never write this policy before the user answers/);
  assert.match(skill, /newly detected version or any routing\/project mismatch still requires review/);
});
